pipeline {

    agent any

    tools {
        jdk 'JDK-21'
        maven 'MAVEN3'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('GUI Elements Automation Framework') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('GUI Elements Automation Framework') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('GUI Elements Automation Framework') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {

        always {
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}
