pipeline {

    agent any

    tools {
        jdk 'JDK-21'
        maven 'MAVEN3'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('GUI Elements Automation Framework') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('GUI Elements Automation Framework') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('GUI Elements Automation Framework') {
                    bat 'mvn package'
                }
            }
        }

        stage('Verify Report') {
            steps {
                dir('GUI Elements Automation Framework') {
                    bat 'dir /s'
                }
            }
        }
    }

    post {

        always {

            // Archive JAR
            archiveArtifacts artifacts: '**/target/*.jar',
                             allowEmptyArchive: true

            // Publish Extent Report
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'GUI Elements Automation Framework/test-output',
                reportFiles: 'ExtentReport.html',
                reportName: 'Extent Report'
            ])
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}
